server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
      show_sql: true
  output:
    ansi:
      enabled: always

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jwt:
    key: ${JWT_KEY}

  elasticsearch:
    uris: "http://${ELASTIC_HOST}:${ELASTIC_PORT}"



logging:
  level:
    '[oxahex.asker.server]': DEBUG
