server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
        use_sql_comments: true
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: ${SMTP_PORT}
    username: ${SMTP_USER_NAME}
    password: ${SMTP_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/google

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jwt:
    key: ${JWT_KEY}

  elasticsearch:
    uris: "http://${ELASTIC_HOST}:${ELASTIC_PORT}"



logging:
  level:
    '[oxahex.asker.server]': DEBUG
    org:
      springframework:
        transaction:
          interceptor: debug
        jdbc:
          datasource: debug
        orm:
          jpa:
            JpaTransactionManager: debug
        hibernate:
          resource:
            transaction: debug

