server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.user.name}
    password: ${db.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: ${smtp.port}
    username: ${smtp.user.name}
    password: ${smtp.key}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth.google.client.id}
            client-secret: ${oauth.google.client.secret}
            scope:
              - profile
              - email
            authorization-grant-type: authorization_code

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}

  jwt:
    key: ${jwt.key}

#  elasticsearch:
#    uris: "http://${ELASTIC_HOST}:${ELASTIC_PORT}"



logging:
  level:
    '[oxahex.asker.server]': info
